name: Local Setup Test
on: [push]
jobs:
  mac_nix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install Python Dependencies
        run: |
          poetry install
      - name: Run local unit tests
        run: |
          poetry run pytest tests/unit
      - name: Run local integration tests
        run: |
          poetry run pytest tests/integration

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install Python Dependencies
        run: |
          scripts\install.bat
          poetry install
      - name: Run local unit tests
        run: |
          poetry run pytest tests/unit
      # This doesn't work at the moment because running spark locally on Windows
      # requires a special setup for Hadoop
      # TODO: https://cwiki.apache.org/confluence/display/HADOOP2/WindowsProblems
      # - name: Run local integration tests
      #   run: |
      #     poetry run pytest tests/integration
